/// \file
/// \ingroup tutorial_tree
/// \notebook -nodraw
/// Copy a subset of a Tree to a new Tree, one branch in a separate file.
///
/// One branch of the new Tree is written to a separate file
/// The input file has been generated by the program in `$ROOTSYS/test/Event`
/// with the command `Event 1000 1 1 1`
///
/// \macro_code
///
/// \author Rene Brun

#include <sstream>
#include <string>
#include <sys/stat.h>
#include "TFile.h"
#include "TTree.h"

void copytree2(const std::string& runNumber) {

   //gSystem->Load("$ROOTSYS/test/libEvent");

   //Get old file, old tree and set top branch address
   TFile *oldfile = new TFile(("/eos/uscms/store/user/cmstestbeam/BTL_ETL/2018_06/data/VME/RECO/v5_noMeas/DataVMETiming_Run"+runNumber+".root").c_str(),"READ");
   TTree *oldtree = (TTree*)oldfile->Get("pulse");

   //Event *event   = new Event();
   //oldtree->SetBranchAddress("event",&event);
   oldtree->SetBranchStatus("*",1);
   oldtree->SetBranchStatus("channel",0);
   oldtree->SetBranchStatus("time",0);


   //Create a new file + a clone of old tree header. Do not copy events
   TFile *newfile = new TFile(("/eos/uscms/store/user/cmstestbeam/BTL_ETL/2018_06/data/VME/RECO/v5_noMeas/nopulse/DataVMETiming_Run"+runNumber+".root").c_str(),"recreate");
   TTree *newtree = oldtree->CloneTree(0);

   //Divert branch fH to a separate file and copy all events
   newtree->CopyEntries(oldtree);

   newtree->Print();
   newfile->Write();
   delete oldfile;
   delete newfile;
}
