#!/bin/bash
root -l -b -q rereco.C+\(\"ntuple_3mmLYSO_3mmSiPM_x0\"\)
root -l -b -q rereco.C+\(\"ntuple_3mmLYSO_4mmSiPM_x0\"\)
root -l -b -q rereco.C+\(\"ntuple_3mmLYSO_6mmSiPM_x0\"\)
root -l -b -q rereco.C+\(\"ntuple_3mmLYSO_10mmSiPM_x0\"\)
root -l -b -q rereco.C+\(\"ntuple_4mmLYSO_3mmSiPM_x0\"\)
root -l -b -q rereco.C+\(\"ntuple_4mmLYSO_4mmSiPM_x0\"\)
root -l -b -q rereco.C+\(\"ntuple_4mmLYSO_6mmSiPM_x0\"\)
root -l -b -q rereco.C+\(\"ntuple_4mmLYSO_10mmSiPM_x0\"\)

root -l -b -q rereco.C+\(\"ntuple_3mmLYSO_3mmSiPM_x0_md\"\)
root -l -b -q rereco.C+\(\"ntuple_3mmLYSO_4mmSiPM_x0_md\"\)
root -l -b -q rereco.C+\(\"ntuple_3mmLYSO_6mmSiPM_x0_md\"\)
root -l -b -q rereco.C+\(\"ntuple_3mmLYSO_10mmSiPM_x0_md\"\)
root -l -b -q rereco.C+\(\"ntuple_4mmLYSO_3mmSiPM_x0_md\"\)
root -l -b -q rereco.C+\(\"ntuple_4mmLYSO_4mmSiPM_x0_md\"\)
root -l -b -q rereco.C+\(\"ntuple_4mmLYSO_6mmSiPM_x0_md\"\)
root -l -b -q rereco.C+\(\"ntuple_4mmLYSO_10mmSiPM_x0_md\"\)

root -l -b -q rereco.C+\(\"ntuple_3mmLYSO_3mmSiPM_x5\"\)
root -l -b -q rereco.C+\(\"ntuple_3mmLYSO_4mmSiPM_x5\"\)
root -l -b -q rereco.C+\(\"ntuple_3mmLYSO_6mmSiPM_x5\"\)
root -l -b -q rereco.C+\(\"ntuple_3mmLYSO_10mmSiPM_x5\"\)
root -l -b -q rereco.C+\(\"ntuple_4mmLYSO_3mmSiPM_x5\"\)
root -l -b -q rereco.C+\(\"ntuple_4mmLYSO_4mmSiPM_x5\"\)
root -l -b -q rereco.C+\(\"ntuple_4mmLYSO_6mmSiPM_x5\"\)
root -l -b -q rereco.C+\(\"ntuple_4mmLYSO_10mmSiPM_x5\"\)

root -l -b -q rereco.C+\(\"ntuple_3mmLYSO_3mmSiPM_x5_md\"\)
root -l -b -q rereco.C+\(\"ntuple_3mmLYSO_4mmSiPM_x5_md\"\)
root -l -b -q rereco.C+\(\"ntuple_3mmLYSO_6mmSiPM_x5_md\"\)
root -l -b -q rereco.C+\(\"ntuple_3mmLYSO_10mmSiPM_x5_md\"\)
root -l -b -q rereco.C+\(\"ntuple_4mmLYSO_3mmSiPM_x5_md\"\)
root -l -b -q rereco.C+\(\"ntuple_4mmLYSO_4mmSiPM_x5_md\"\)
root -l -b -q rereco.C+\(\"ntuple_4mmLYSO_6mmSiPM_x5_md\"\)
root -l -b -q rereco.C+\(\"ntuple_4mmLYSO_10mmSiPM_x5_md\"\)

